export const socialMediaData = [
  {
    name: "@nathanf",
    icon: "iconFacebook",
    followers: "1987",
    description: "Followers",
    followersChange: "12 Today",
    borderClass: "border-blue",
    upArrow: "upArrow",
  },
  {
    name: "@nathanf",
    icon: "iconTwitter",
    followers: "1044",
    description: "Followers",
    followersChange: "99 Today",
    borderClass: "border-cyan",
    upArrow: "upArrow",
  },
  {
    name: "@realnathanf",
    icon: "iconInstagram",
    followers: "11k",
    description: "Followers",
    followersChange: "1099 Today",
    borderClass: "border-gradiant",
    upArrow: "upArrow",
  },
  {
    name: "Nathan F",
    icon: "iconYoutube",
    followers: "8239",
    description: "Subscribers",
    followersChange: "144 Today",
    downClass: "downgrade",
    downArrow: "downArrow",
    borderClass: "border-red",
  },
];
